import { cleanEnv, str, num, bool } from 'envalid';

const env = cleanEnv(process.env, {
  PORT: num({ default: 3000 }),
  NODE_ENV: str({ choices: ['development', 'production', 'test'] as const, default: 'development' }),
  MONGODB_URI: str(),
  JWT_SECRET: str({ length: 32 }),
  JWT_REFRESH_SECRET: str({ length: 32 }),
  JWT_EXPIRES_IN: str({ default: '15m' }),
  JWT_REFRESH_EXPIRES_IN: str({ default: '7d' }),
  RESEND_API_KEY: str(),
  EMAIL_FROM: str({ default: 'noreply@shopsphere.com' }),
  STRIPE_SECRET_KEY: str(),
  STRIPE_PUBLISHABLE_KEY: str(),
  STRIPE_WEBHOOK_SECRET: str(),
  STRIPE_SUCCESS_URL: str(),
  STRIPE_CANCEL_URL: str(),
  AWS_ACCESS_KEY_ID: str(),
  AWS_SECRET_ACCESS_KEY: str(),
  AWS_REGION: str({ default: 'us-east-1' }),
  S3_BUCKET_NAME: str(),
  ALGOLIA_APP_ID: str(),
  ALGOLIA_ADMIN_KEY: str(),
  ALGOLIA_SEARCH_KEY: str(),
  ALGOLIA_INDEX_NAME: str({ default: 'products' }),
  GOOGLE_CLIENT_ID: str(),
  GOOGLE_CLIENT_SECRET: str(),
  GOOGLE_CALLBACK_URL: str({ default: '/api/auth/oauth/google/callback' }),
  FACEBOOK_APP_ID: str(),
  FACEBOOK_APP_SECRET: str(),
  FACEBOOK_CALLBACK_URL: str({ default: '/api/auth/oauth/facebook/callback' }),
  RATE_LIMIT_WINDOW_MS: num({ default: 15 * 60 * 1000 }),
  RATE_LIMIT_MAX_REQUESTS: num({ default: 100 }),
  CSRF_SECRET: str({ length: 32 }),
  BASE_URL: str({ default: 'http://localhost:5173' }),
  API_BASE_URL: str({ default: 'http://localhost:3000/api' }),
});

export default env;