-- No database required — application uses MongoDB for data persistence.
-- Supabase is used only for monorepo structure; all data operations handled by Express/MongoDB backend.
-- File exists for project consistency and tooling requirements.