-- No database required — ShopSphere uses MongoDB (Mongoose) for data persistence.
-- Supabase PostgreSQL services are not used in this project.
-- All data operations handled via Express.js API with MongoDB backend.